# Generated by Django 6.0 on 2025-12-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ads', 'ADS'), ('narration', 'Narration'), ('dubbing', 'Dubbing'), ('books', 'Audio Books'), ('other', 'Other')], default='other', max_length=50)),
                ('audio_file', models.FileField(upload_to='audio/%Y/%m/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to show on the Home page showcase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
