# Generated by Django 6.0 on 2025-12-17 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceover',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
