# Generated by Django 6.0 on 2025-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_voiceover_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceover',
            name='category',
            field=models.CharField(choices=[('ads', 'ADS'), ('narration', 'Narration'), ('documentary', 'Documentary'), ('dubbing', 'Dubbing'), ('books', 'Audio Books'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
