# Generated by Django 5.0.1 on 2025-12-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_voiceover_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceover',
            name='category',
            field=models.CharField(choices=[('ads', 'ADS'), ('narration', 'Narration'), ('documentary', 'Documentary'), ('dubbing', 'Dubbing'), ('books', 'Audio Books'), ('radio', 'Radio'), ('ivr', 'IVR'), ('podcast', 'Podcast'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
