# Generated by Django 5.0.1 on 2025-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceover',
            name='category',
            field=models.CharField(choices=[('ads', 'ADS'), ('narration', 'Narration'), ('documentary', 'Documentary'), ('dubbing', 'Dubbing'), ('books', 'Audio Books'), ('radio', 'Radio'), ('ivr', 'IVR'), ('podcast', 'Podcast'), ('elearning', 'E-Learning'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
